/*
TEM COMO OBJETIVO DESTACAR ARTIGOS OS ARTIGOS SEM STOCK
OBS: DESCONSIDERAR ARTIGOS BLOQUEADOS E SERVICOS
*/
WITH mydata AS (
  SELECT 
    REFERENCIA
  , DESIGNACAO
  , ABS ( CONVERT (NUMERIC (18,2) , STOCK_DISP) ) AS STOCK_DISP
  , CONVERT (NUMERIC (18,2) ,PRECO )              AS PRECO
  , CONVERT (NUMERIC (18,2) ,PRECO_CUSTO )        AS PRECO_CUSTO
  , UPPER ( COD_FAMILIA )                         AS FAMILIA
  FROM dbo.dim_artigo
  WHERE SERVICO    = 0
  AND   BLOQUEADO  = 0
  AND   STOCK_DISP <= 0
)
SELECT 
  DENSE_RANK() OVER (ORDER BY STOCK_DISP DESC, (PRECO - PRECO_CUSTO) DESC) AS RANK_ARTIGO
, m.*
FROM mydata m